#!/bin/bash
sudo apt-get -y update
sudo apt-get -y install ruby
sudo apt-get -y install wget
cd /home/ubuntu
wget https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo apt-get install -y python3-pip
sudo pip3 install awscli
sudo apt-get -y install nginx
sudo apt-get -y install python3-venv
python3 -m venv env
source env/bin/activate
pip3 install django
pip3 install gunicorn
sudo apt-get install -y supervisor
git clone https://github.com/RaghuvirDav9/django.git
sudo cp /home/ubuntu/django/resources/gunicorn.conf /etc/supervisor/conf.d/
sudo cp /home/ubuntu/django/resources/django.conf /etc/nginx/sites-available/
OUTPUT=$(curl http://instance-data/latest/meta-data/public-hostname)
sudo sed -i 's/$region/'${OUTPUT}'/g' /etc/nginx/sites-available/django.conf
sudo cp -f /home/ubuntu/django/resources/nginx.conf /etc/nginx/nginx.conf
sudo mkdir /var/log/gunicorn
sudo ln /etc/nginx/sites-available/django.conf /etc/nginx/sites-enabled/
sudo service nginx restart
sudo supervisorctl reread
sudo supervisorctl update
