#!/bin/bash
# cd /home/ubuntu
# sudo apt-get update
# sudo apt-get install python3
# python3 -m venv env
# source env/bin/activate
# pip3 install django
# pip3 install nginx
echo "installing dependencies"
